Algoritmo "media_ponderada"

Var

    N, i : inteiro
 media,n1,n2,n3:real

Inicio

    escreva("Quantos casos você  vai digitar? ")
    leia(N)

    para i de 1 ate N faca
       escreval("Digite 3 números: ")
       leia(n1)
       leia(n2)
       leia(n3)
       
     media <- (n1*2+n2*3+n3*5)/10
       
      escreval("MEDIA =",media:3:1)


       
      fimpara


Fimalgoritmo





Fimalgoritmo