Algoritmo "pares_consecutivos"

Var

x,soma:inteiro;

Inicio
    escreval("Digite o numero inteiro")
      leia(x)
      
           enquanto X <> 0 faca
       se x % 2 <> 0 então
      
       x <- x + 1
      
      fimse
      
    soma <- 5 * x + 20
     escreval("Soma é igual a ",soma)
     
       escreva("Digite um numero inteiro: ")
      leia(X)
     
          fimenquanto

Fimalgoritmo